config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
    
    namespace :admin do
      resources :users
      resources :books
      resources :authors
      get '/dashboard', to: 'dashboard#home'
      resources :categories
      resources :publishers
      resources :borrows
      get "/showborrow", to:"borrows#showborrow"
      get "/showreturn", to:"borrows#showreturn"
      root to: 'dashboard#home'
   end

  resources :notifications
  resources :borrows
  resources :publishers
  resources :categories
  resources :authors
  
  resources :books do
    resources :borrows
    resources :reviews
  end
  devise_for :users
  root to: "home#index"
  get "/about", to: "home#about"
  get "/showborrow", to:"borrows#showborrow"
  get "/showreturn", to:"borrows#showreturn"
  get "/booksort", to:"books#indexsort"
  get "/bookfilter", to:"books#indexfilter"
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  has_many :author_books, dependent: :destroy
  has_many :authors, through: :author_books
  has_many :borrows, dependent: :destroy
  has_many :users, through: :borrows
  belongs_to :category, optional: true
  belongs_to :publisher, optional: true
  has_many :reviews, dependent: :destroy
  accepts_nested_attributes_for :author_books
  validates_format_of :name, with: /\A(?!^\d+$)^.+$\z/
  validates :borrow_fee, numericality: { greater_than: 0 }, allow_nil: true
  before_create {|book| book.name = book.name.titleize }

  def self.hotbooks 
    all.order("total_borrow DESC")[0]
  end

  def self.newest
    all.order("id DESC").limit(3) 
  end

  def self.sort(param)
    if param == "Select"
      all 
    elsif param == "Newest books"
      all.order("published_date desc")
    elsif param == "Oldest books"
      all.order("published_date asc")
    elsif param == "Fee low to high"
      all.order("borrow_fee asc")
    elsif param == "Fee high to low"
      all.order("borrow_fee desc")
    elsif param == "Most borrow"
      all.order("total_borrow desc")
    else
      all
    end 
  end

  def self.filter(query)
    book = Book.includes(:authors).references(:author_books)
    author_id = query[0] unless query[0] == ""
    category_id = query[1] unless query[1] == ""
    publisher_id = query[2] unless query[2] == ""
    if author_id && category_id && publisher_id
      book.where("authors.id = ? AND books.category_id = ? AND books.publisher_id = ?",author_id,category_id,publisher_id)
    elsif author_id
      if category_id 
        book.where("authors.id = ? AND books.category_id = ?",author_id,category_id)
      elsif publisher_id
        book.where("authors.id = ? AND books.publisher_id = ?",author_id,publisher_id)
      else
        book.where("authors.id = ?",author_id)
      end
    elsif category_id
      if author_id
        book.where("authors.id = ? AND books.category_id = ?",author_id,category_id)
      elsif publisher_id
        book.where("books.category_id = ? AND books.publisher_id = ?",category_id,publisher_id)
      else
        book.where("books.category_id = ?",category_id)
      end
    elsif publisher_id
      if author_id
        book.where("authors.id = ? AND books.publisher_id = ?",author_id,publisher_id)
      elsif category_id
        book.where("books.category_id = ? AND books.publisher_id = ?",category_id,publisher_id)
      else
        book.where("books.publisher_id = ?",publisher_id)
      end
    else
      all
    end 
  end
  
  def self.search(query)
    book_author = Book.includes(:authors).references(:author_books)
    book_pub = book_author.includes(:publisher)
    book = book_pub.includes(:category)
    if query
      book.where("books.name LIKE '%#{query.titleize}%' OR
        authors.author_name LIKE '%#{query.titleize}%' OR
        categories.name LIKE '%#{query.capitalize}%' OR
        publishers.publisher_name LIKE '%#{query.upcase}%' OR
        books.description LIKE '%#{query}%'
        ")
    else
      all
    end
  end

  def self.exist_quantity
    totals = 0
    all.each do |book|
      totals += book.quantity_in_stock
    end
    totals
  end

end

app/controllers/admin/books_controller.rb
class Admin::BooksController < AdminController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_user!
  add_flash_types :success, :warning, :danger, :info

  #authorization with cancancan
  load_and_authorize_resource     

  def index 
    @book = Book.all
  end

  def show
  end

  def new
    @book = Book.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params)
    @book.created_at = Time.now
    if @book.save
      redirect_to request.referrer
      flash[:success] = "Book was successfully created! #{view_context.link_to("Do you want check the #{@book.name} book", "#{@book.id}")}"
    else
      respond_to do |format|
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html {redirect_to admin_books_path, success:"Book was successfully updated!"}
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @book.destroy
    redirect_to request.referrer
    flash[:info] = "Book was successfully destroyed!"
  end

  private

  def set_book 
    @book = Book.find(params[:id]) 
  end

  def book_params
    params.require(:book).permit(:name,
       :description,
       :published_date,
       :publisher_id,
       :borrow_fee,
       :quantity,
       :quantity_in_stock,
       :image,
       :category_id,
       author_books_attributes: [:id, author_attributes: [:id, :author_name]])
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index indexsort indexfilter] 
  add_flash_types :success, :warning, :danger, :info

  #authorization with cancancan
  load_and_authorize_resource
  skip_load_and_authorize_resource only: [:index, :show, :indexsort, :indexfilter]

  # GET /books or /books.json
  def index
    @books = Book.search(params[:search]).paginate(:page => params[:page], :per_page => 6)
  end

  def indexsort 
    param = params[:sort]
    @books = Book.sort(param).paginate(:page => params[:page], :per_page => 6)
    render :index
  end

  def indexfilter
    query = [params[:author_id],params[:category_id],params[:publisher_id]]
    @books = Book.filter(query).paginate(:page => params[:page], :per_page => 6)
    render :index
  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)
    @book.created_at = Time.now
    respond_to do |format|
      if @book.save
        format.html { redirect_to request.referrer,
        success: "Book was successfully created! #{view_context.link_to("Do you want check the #{@book.name} book", "#{@book.id}")}"}
      else
        format.html { redirect_to request.referrer, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html {redirect_to books_path, success:"Book was successfully updated!"}
      else
        format.html { redirect_to request.referrer, danger:"Something went wrong!"}
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    redirect_to books_path
    flash[:info] = "Book was successfully destroyed!"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book 
    @book = Book.find(params[:id]) 
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:name,
       :description,
       :published_date,
       :publisher_id,
       :borrow_fee,
       :quantity,
       :quantity_in_stock,
       :image,
       :category_id,
       author_books_attributes: [:id, author_attributes: [:id, :author_name]])
  end
  #as
end

app/helpers/admin/books_helper.rb
module Admin::BooksHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/admin/books/_author_book_fields.html.erb
<div class="authors">
  <%= form.fields_for :author do |author_form| %>
  <%= render 'author_fields', form: author_form %>
  <%end%>
</div>

app/views/admin/books/_author_fields.html.erb
<div class="nested-fields">
   <div class="field form-group">
   <%= form.label "Author name" %>
   <%= form.text_field :author_name,placeholder:"Author name", class:"form-control" %>
   </div>
   <%= link_to_remove_association "Delete", form ,class:"btn btn-dark"%>
</div>

app/views/admin/books/_form.html.erb
<div class="row m-5">
<%= form_for ([:admin, book]) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, placeholder:"Book name", class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description , placeholder:"Description about book", class:"form-control"%>
  </div>
  <div class="field form-group">
    <%= form.label :category%>
    <%= form.collection_select :category_id, Category.all, :id, :name%>
  </div>
 <div class="authorbooks">
  <%= form.fields_for :author_books do |author_books_form| %>
    <%= render 'author_book_fields',form: author_books_form%>
    <% end %>
     <div class="links">
  <%= link_to_add_association 'Add author', form, :author_books, wrap_object: Proc.new { |author_book| author_book.build_author; author_book },form_name: 'form',class:"btn btn-info"%>
  </div>
  </div>
  <div class="field form-group">
    <%= form.label :published_date %>
    <%= form.date_field :published_date,class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :publisher %>
    <%= form.collection_select :publisher_id, Publisher.all, :id, :publisher_name %>
  </div>

  <div class="field form-group">
    <%= form.label :borrow_fee %>
    <%= form.text_field :borrow_fee, placeholder:"Fee borrow book" ,class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :quantity %>
    <%= form.number_field :quantity, placeholder:"Quanity" ,class:"form-control"%>
  </div>

  <div class="field form-group">
    <%= form.label :quantity_in_stock %>
    <%= form.number_field :quantity_in_stock, placeholder:"Quantity in stock" ,class:"form-control"%>
  </div>
  <div class="field">
    <%= form.label :image%>
    <%= form.file_field :image%>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/admin/books/edit.html.erb
<h1>Edit book <%=@book.name%></h1>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link" href="/admin/books/<%=@book.id%>"><i class="fas fa-info-circle"></i> Show</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="/admin/books/<%=@book.id%>/edit"><i class="far fa-edit"></i> Edit</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="/admin/books/<%=@book.id%>" data-method="delete"><i class="fas fa-trash-alt"></i> Delete</a>
  </li>
</ul>
<%= render 'form', book: @book %>

app/views/admin/books/index.html.erb
<h1>Books</h1>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'Books',admin_books_path,class:"nav-link"%>
  </li>
  <li class="nav-item">
     <%= link_to 'New book',new_admin_book_path,class:"nav-link"%>
  </li>
</ul>
<div class="p-4 bg-light">
    <%= form_tag admin_books_path, method: 'get', class:"input-group" do %>
        <input id="bookinput" class="form-control input-small" name="search" placeholder="Search" type="search">
        <span class="input-group-btn">
            <button class="btn btn-primary" type="submit">
            Search
            </button>
        </span>
    <% end %>
</div>
<table id="bookadmin" class="table table-striped">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Book</th>
      <th scope="col">Image</th>
      <th scope="col">Published date</th>
      <th scope="col">Borrow fee</th>
      <th scope="col">Quantity</th>
      <th scope="col">Quantity in stock</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @book.each do |book| %>
      <tr>
        <th scope="row"><%= book.id %></th>
        <td><%= book.name %></td>
        <td><%= image_tag book.image, class: "admin-book-img" if book.image.present?%></td>
        <td><%= book.published_date%></td>
        <td><%= book.borrow_fee%></td>
        <td><%= book.quantity%></td>
        <td><%= book.quantity_in_stock%></td>
        <td class="px-5" style="text-align: right">
          <a href="/admin/books/<%=book.id%>"><i class="fas fa-info-circle"></i></a>
          <a href="/admin/books/<%=book.id%>/edit"><i class="far fa-edit"></i></a>
          <a href="/admin/books/<%=book.id%>" data-method="delete"><i class="fas fa-trash-alt"></i></a>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<script type="text/javascript">
 var table = $('#bookadmin').DataTable({"bLengthChange": false, "sPaginationType": "full_numbers","pageLength": 5,sDom: 'lrtip'});
$('#bookinput').keyup(function(){
      table.search($(this).val()).draw() ;
})
</script>

app/views/admin/books/new.html.erb
<h1>Create book</h1>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to 'Books',admin_books_path,class:"nav-link"%>
  </li>
  <li class="nav-item">
     <%= link_to 'New book',new_admin_book_path,class:"nav-link"%>
  </li>
</ul>
<%= render 'form', book: @book %>

app/views/admin/books/show.html.erb
<h1>Book <%=@book.name%></h1>
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" href="/admin/books/<%=@book.id%>"><i class="fas fa-info-circle"></i> Show</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/admin/books/<%=@book.id%>/edit"><i class="far fa-edit"></i> Edit</a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="/admin/books/<%=@book.id%>" data-method="delete"><i class="fas fa-trash-alt"></i> Delete</a>
    </li>
</ul>
<dt>
    <span class="label label-info">
        Author
    </span>
    <div class="p-4 bg-light">
        <% @book.author_books.each do |author_book|%>
        <li>
            <%= author_book.author.author_name%>
        </li>
        <%end%>
    </div>
    <span class="label label-info">
        Publisher
    </span>
    <div class="p-4 bg-light">
        <%= Publisher.find(@book.publisher_id).publisher_name if @book.publisher_id%>
    </div>
    <span class="label label-info">
        Category
    </span>
    <div class="p-4 bg-light">
        <%= Category.find(@book.category_id).name if @book.category_id%>
    </div>
</dt>