config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
    
    namespace :admin do
      resources :users
      resources :books
      resources :authors
      get '/dashboard', to: 'dashboard#home'
      resources :categories
      resources :publishers
      resources :borrows
      get "/showborrow", to:"borrows#showborrow"
      get "/showreturn", to:"borrows#showreturn"
      root to: 'dashboard#home'
   end

  resources :notifications
  resources :borrows
  resources :publishers
  resources :categories
  resources :authors
  
  resources :books do
    resources :borrows
    resources :reviews
  end
  devise_for :users
  root to: "home#index"
  get "/about", to: "home#about"
  get "/showborrow", to:"borrows#showborrow"
  get "/showreturn", to:"borrows#showreturn"
  get "/booksort", to:"books#indexsort"
  get "/bookfilter", to:"books#indexfilter"
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  validates :message, presence: true
  

  def self.update_seen(id)
    notification = Notification.find(id)
    notification.update_column(:seen, true)
  end

  def self.count_notice
    Notification.where(:message => "for staff").count
  end


  def self.count_notice_user(user_id)
    Notification.where("user_id = #{user_id} AND seen = 'false' AND message != 'for staff'").count
  end
  
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: %i[show edit update destroy]
  before_action :authenticate_user!


  #authorization with cancancan
  load_and_authorize_resource

  # GET /notifications or /notifications.json
  def index
    @notifications = Notification.where("user_id = #{current_user.id} AND message != 'for staff'").paginate(:page => params[:page], :per_page => 10).order("created_at DESC, seen")
  end

  # GET /notifications/1 or /notifications/1.json
  def show
    if @notification.seen == false
      Notification.update_seen(@notification.id)
    end
  end

  # DELETE /notifications/1 or /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: "Notification was successfully destroyed." }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def notification_params
      params.require(:notification).permit(:message, :seen, :user_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1 class="d-flex justify-content-center alert alert-primary" role="alert">Notifications</h1>

<div class="list-group ">
  <% @notifications.each do |notification| %>
  <div  class="list-group-item ">
    <small>
       <%=notification.created_at.to_formatted_s(:db)%>
    </small>
  
      <%if notification.seen == false%>
        <%= link_to notification.message, notification, class:"list-group-item-action font-weight-bold" %>
      <% else %>
        <%= link_to notification.message, notification, class:"list-group-item-action"%>
      <% end %>
  </div>
  
  <% end %>

</div>
    <%= will_paginate @books%>
    
<br>
</div>

app/views/notifications/show.html.erb
<div class="container">
<h1 class="d-flex justify-content-center" role="alert">Notification</h1>

<div class="alert alert-primary" role="alert">
  <p>
    <strong>Time</strong>
    <%= @notification.created_at.to_formatted_s(:db) %>
  </p>
  <hr>
  <p>
    <strong>Notification:</strong>
    <%= @notification.message %><br>
    <%= link_to "Click the link to see specific","/borrows/#{@notification.borrow_id}"%><br>
    <%if Borrow.find(@notification.borrow_id).status.include? "returned"%>
    <%= link_to "Go to rate the book", "/books/#{@notification.book_id}"%> 
    <%end%>
  </p>
</div>
<%=link_to '<i class="fas fa-long-arrow-alt-left"> Back</i> '.html_safe, notifications_path, class:"btn btn-primary"%>
</div>