config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
    
    namespace :admin do
      resources :users
      resources :books
      resources :authors
      get '/dashboard', to: 'dashboard#home'
      resources :categories
      resources :publishers
      resources :borrows
      get "/showborrow", to:"borrows#showborrow"
      get "/showreturn", to:"borrows#showreturn"
      root to: 'dashboard#home'
   end

  resources :notifications
  resources :borrows
  resources :publishers
  resources :categories
  resources :authors
  
  resources :books do
    resources :borrows
    resources :reviews
  end
  devise_for :users
  root to: "home#index"
  get "/about", to: "home#about"
  get "/showborrow", to:"borrows#showborrow"
  get "/showreturn", to:"borrows#showreturn"
  get "/booksort", to:"books#indexsort"
  get "/bookfilter", to:"books#indexfilter"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  

  def index
    @hot_book = Book.hotbooks
    @newest_books = Book.newest
  end
  
  def about; end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<%= stylesheet_link_tag 'footer'%>
 <!-- Site footer -->
    <footer class="site-footer">
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">Library website is a destination for you to find and read the best, latest and most complete books in the world with a variety of genres and convenience of use.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Quick Links</h6>
            <ul class="footer-links">
              <li><a href="/">Home</a></li>
              <li><a href="http://scanfcode.com/contact/">Contact Us</a></li>
              <li><a href="http://scanfcode.com/contribute-at-scanfcode/">Contribute</a></li>
              <li><a href="http://scanfcode.com/privacy-policy/">Privacy Policy</a></li>
              <li><a href="http://scanfcode.com/sitemap/">Sitemap</a></li>
            </ul>
          </div>
        </div>
        <hr>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyright &copy; 2021 All Rights Reserved by 
         <a href="https://github.com/Doanchithien">Team 1</a>.
            </p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>   
            </ul>
          </div>
        </div>
      </div>
</footer>

app/views/home/_header.html.erb
<%= stylesheet_link_tag 'header'%>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%=link_to 'Library',root_path,class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <%= form_tag(books_path, :method => "get" ) do%>
      <%= text_field_tag :search, params[:search], placeholder: "Search",:style => "width:550px;height:40px" %>
      <%= button_tag type: 'submit', class: "btn btn-info" do %>
         <i class="fa fa-search"></i>
      <% end %>
      <% end %>
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <%=link_to 'Books',books_path, class:"nav-link"%>
        </li>
        <li class="nav-item">
          <%=link_to 'Authors',authors_path, class:"nav-link"%>
        </li>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Category
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <%Category.all.each do |category|%>
            <%= link_to "#{category.name}", "/categories/#{category.id}",class:"dropdown-item", style:"color:blue"%>
            <%end%>
          </ul>
        </li>
        <%if user_signed_in?%>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Personal
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
            <li><a class="dropdown-item notification" style="color:blue" href="/notifications"><i class="fa fa-bell"></i> Notifications <span class="badge"><%=Notification.count_notice_user(current_user.id) unless Notification.count_notice_user(current_user.id).zero?  %></span></a></li>
            <%=link_to '<i class="fa fa-tasks"></i> Activitys'.html_safe,borrows_path, class:"dropdown-item", style:"color:blue"%>
            <%=link_to '<i class="fa fa-gear"></i> Account settings'.html_safe,edit_user_registration_path, class:"dropdown-item", style:"color:blue"%>
             <%=link_to '<i class="fa fa-sign-out"></i> Log out'.html_safe,destroy_user_session_path,method: :delete, class:"dropdown-item", style:"color:blue"%>
          </ul>
        </li>
        <%else%>
        <li class="nav-item">
          <%= link_to 'Sign in',new_user_session_path,class:"nav-link"%>
        </li>
        <li class="nav-item">
        <%= link_to 'Sign up',new_user_registration_path,class:"nav-link"%>
        </li>
        <%end%>
      </ul>
      </div>
    </div>
  </div>
</nav>

<header>

  <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active" style="background-image: url('https://wallpaperaccess.com/full/124383.jpg')">
        <div class="carousel-caption" style="color:cyan">
          <h1>Digital Library</h1>
          <h3>Let's use our service and we will bring everything to you!</h3>
        </div>
      </div>
      <div class="carousel-item" style="background-image: url('https://i.pinimg.com/originals/d8/2d/72/d82d72723724a47fab10c90da326c295.jpg')">
        <div class="carousel-caption" style="color:cyan">
         <h1>Variety of books</h1>
          <h3>We have all the books you need!Let's see it!</h3>
        </div>
      </div>
      <div class="carousel-item" style="background-image: url('https://1.bp.blogspot.com/-_M_C9G0tdiE/Xnc1nT7abEI/AAAAAAAAEy8/t956U8Xwy5sOsSv68z8pgeQnJ7BxTXyCQCLcBGAsYHQ/w1200-h630-p-k-no-nu/Anime%2BLibrary%2BBackground%2B1.png')">
        <div class="carousel-caption">
          <h1>Convienient</h1>
          <h3>Just by click and you can find all you need</h3>
        </div>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</header>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<%= stylesheet_link_tag 'home'%>
 <section class="dark">
	<div class="container py-4">
        <h1 class="h1 text-center" id="pageHeaderTitle" style="color:#00008B">Most Borrowed Book</h1>
		<% if @hot_book%>
		<article class="postcard dark blue">
			<a class="postcard__img_link" href="/books/<%= @hot_book.id%>">
				<img class="postcard__img" src="<%= url_for(@hot_book.image) if@hot_book.image.present?%>" alt="Image Title" />
			</a>
			<div class="postcard__text">
				<h1 class="postcard__title blue"><a href="/books/<%= @hot_book.id%>"><%= @hot_book.name%></a></h1>
				<div class="postcard__subtitle small">
					<time datetime="2020-05-25 12:00:00">
						<i class="fas fa-calendar-alt mr-2"></i> <%= @hot_book.created_at%>
						<br><i class="fas fa-comments-dollar"> <%= @hot_book.borrow_fee%></i><br>
                    	<%if @hot_book.rating.present?%> 
        				<%@hot_book.rating.times do%>
        				<i class="fa fa-star checked" style="color:yellow"></i>
        				<%end%>    
        			<%end%>   
					<br><span>Total borrow : <%= @hot_book.total_borrow%></span>
					</time>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt"><%= @hot_book.description%></div>
				<ul class="postcard__tagbox">
                    <% @hot_book.author_books.each do |authorbook| %>
					<li class="tag__item play blue">
						<a href="/authors/<%= authorbook.author.id%>"><i class="fas fa-tag"></i> <%= authorbook.author.author_name%></a>
					</li>
                    <%end%>
					<li class="tag__item play blue">
						<a href="/publishers/<%= @hot_book.publisher_id%>"><i class="fas fa-tag"></i> <%= Publisher.find(@hot_book.publisher_id).publisher_name if @hot_book.publisher_id%></a>
					</li>
                    <li class="tag__item play blue">
						<a href="/categories/<%= @hot_book.category_id%>"><i class="fas fa-tag"></i> <%= Category.find(@hot_book.category_id).name if @hot_book.category_id%></a>
					</li>
				</ul>
				<%= form_for ([@hot_book, @hot_book.borrows.build]) do |f|%>
          			<%= f.hidden_field :status, value: "waiting accept"%>
                <%if user_signed_in?%>
                	<% unless current_user.borrows.where( {book_id: @hot_book.id, status: ["waiting accept", "accept"]}).exists? || @hot_book.quantity_in_stock.nil? %>
                    	<%= button_tag type: 'submit', class: "btn btn-primary", data: {confirm: "Do you want borrow #{@hot_book.name}"} do %>
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    	<% end %>
                	<%end%>
            	<%else%>
              		<%= button_tag type: 'submit', class: "btn btn-primary" do %>
                  	<i class="fa fa-plus" aria-hidden="true"></i>
                	<% end %>
            	<%end%>
        		<%end%>    
			</div>
		</article>
		<%end%>
        <h1 class="h1 text-center" id="pageHeaderTitle" style="color:#00008B">Newest Book</h1>
        <% @newest_books.each do |book|%>
		<article class="col postcard dark red">
			<a class="postcard__img_link" href="/books/<%= book.id%>">
				<img class="postcard__img" src="<%= url_for(book.image) if book.image.present?%>" alt="Image Title" />	
			</a>
			<div class="postcard__text">
				<h1 class="postcard__title red"><a href="/books/<%= book.id%>"> <%= book.name%></a></h1>
				<div class="postcard__subtitle small">
					<time datetime="2020-05-25 12:00:00">
						<i class="fas fa-calendar-alt mr-2"></i> <%= book.published_date%>
						<br><i class="fas fa-comments-dollar"> <%= book.borrow_fee%></i><br>
                    	<%if book.rating.present?%> 
        				<%book.rating.times do%>
        				<i class="fa fa-star checked" style="color:yellow"></i>
        				<%end%>    
        				<%end%>   
					<br><span>Total borrow : <%= book.total_borrow%></span>
					</time>
				</div>
				<div class="postcard__bar"></div>
				<div class="postcard__preview-txt"><%= book.description%></div>
				<ul class="postcard__tagbox">
                    <% book.author_books.each do |authorbook|%>
					<li class="tag__item play red">
						<a href="/authors/<%= authorbook.author.author_name%>"><i class="fas fa-tag"></i> <%= authorbook.author.author_name%></a>
					</li>
                    <%end%>
					<li class="tag__item play blue">
						<a href="/publishers/<%= book.publisher_id%>"><i class="fas fa-tag"></i> <%= Publisher.find(book.publisher_id).publisher_name if book.publisher_id%></a>
					</li>
                    <li class="tag__item play blue">
						<a href="/categories/<%= book.category_id%>"><i class="fas fa-tag"></i> <%= Category.find(book.category_id).name if book.category_id%></a>
					</li>
				</ul>
				<%= form_for ([book, book.borrows.build]) do |f|%>
          			<%= f.hidden_field :status, value: "waiting accept"%>
            			<%if user_signed_in?%>
                			<% unless current_user.borrows.where( {book_id: book.id, status: ["waiting accept", "accept"]}).exists? || book.quantity_in_stock.nil? %>
                    		<%= button_tag type: 'submit', class: "btn btn-primary", data: {confirm: "Do you want borrow #{book.name}"} do %>
                        	<i class="fa fa-plus" aria-hidden="true"></i>
                    		<% end %>
                		<%end%>
            			<%else%>
              			<%= button_tag type: 'submit', class: "btn btn-primary" do %>
                  		<i class="fa fa-plus" aria-hidden="true"></i>
                		<% end %>
            		<%end%>
        		<%end%>    
			</div>
		</article>
        <%end%>
	</div>
</section>