config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
    
    namespace :admin do
      resources :users
      resources :books
      resources :authors
      get '/dashboard', to: 'dashboard#home'
      resources :categories
      resources :publishers
      resources :borrows
      get "/showborrow", to:"borrows#showborrow"
      get "/showreturn", to:"borrows#showreturn"
      root to: 'dashboard#home'
   end

  resources :notifications
  resources :borrows
  resources :publishers
  resources :categories
  resources :authors
  
  resources :books do
    resources :borrows
    resources :reviews
  end
  devise_for :users
  root to: "home#index"
  get "/about", to: "home#about"
  get "/showborrow", to:"borrows#showborrow"
  get "/showreturn", to:"borrows#showreturn"
  get "/booksort", to:"books#indexsort"
  get "/bookfilter", to:"books#indexfilter"
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :books, dependent: :destroy
  validates :name, presence: true, uniqueness: true, format: {with: /\A[[:alpha:][:blank:]]+\z/ }
  before_create {|category| category.name = category.name.capitalize}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < AdminController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!
  add_flash_types :success, :warning, :danger, :info

  #authorization with cancancan
  load_and_authorize_resource

  def index
    @categories = Category.all
  end


  def show; end

  def new
    @category = Category.new
  end


  def edit; end


  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to request.referrer 
        flash[:success] = "Category was successfully created!  #{view_context.link_to("Do you want check the #{@category.name}", "#{@category.id}")}"
      else
        respond_to do |format|
          format.html {render :new, status: :unprocessable_entity}
        end
      end
  end


  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html {redirect_to admin_categories_path, success:"Category was successfully updated!"}
      else
        format.html {render :edit, status: :unprocessable_entity}
      end
    end
  end


  def destroy
    @category.destroy
    redirect_to request.referrer
    flash[:info] = "Category was successfully destroyed!"
  end

  private


  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[show index]
  add_flash_types :success, :warning, :danger, :info

  #authorization with cancancan
  load_and_authorize_resource

  # GET /categories or /categories.json
  def index
    @categories = Category.all.paginate(:page => params[:page], :per_page => 12).order("name ASC")
  end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)
      if @category.save
        redirect_to request.referrer 
        flash[:success] = "Category was successfully created!  #{view_context.link_to("Do you want check the #{@category.name}", "#{@category.id}")}"
      else
        respond_to do |format|
          format.html {redirect_to request.referrer, danger: "Something went wrong!"}
        end
      end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html {redirect_to categories_url, success:"Category was successfully updated!"}
      else
        format.html {redirect_to request.referrer, danger: "Something went wrong!"}
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    redirect_to categories_url
    flash[:info] = "Category was successfully destroyed!"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :description)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<div class="container">
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>
</div>

app/views/categories/index.html.erb
<div class="container">
<h2 style="text-align:center">Categories</h2>
<div class="row">
<%@categories.each do |category|%>
<div class="col-4">
<a href="/categories/<%=category.id%>">
<div class="card" style="width: 18rem;margin:10px">
  <div class="card-body">
    <h5 class="card-title" style="color:blue"><%=category.name%></h5>
    <h6 class="card-subtitle mb-2 text-muted" style="color:blue"><%=category.description%></h6>
  </div>
</div>
</a>
</div>
<%end%>
</div>
<%= will_paginate @categories%>
</div>

app/views/categories/new.html.erb
<div class="container">
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>
</div>

app/views/categories/show.html.erb
<% books = @category.books.paginate(:page => params[:page], :per_page => 12)%>
<div class="container">
<%=link_to '<i class="fas fa-long-arrow-alt-left"> Back</i> '.html_safe, :back, class:"btn btn-primary",style: "margin:20px"%>
<h3 style="text-align:center">Category <%= @category.name%></h3>
<div class="row">
<%books.each do |book|%>
<div class="col-4">
<div class="card" style="width: 18rem;margin:20px;">
  <div class="card-body">
    <h5 class="card-title" style="color:black"><%= book.name%></h5>
    <p class="card-text">Borrow fee: <%=book.borrow_fee%> VND</p>
    <p class="card-text">Number of borrowings : <%=book.total_borrow%></p>
     <%= form_for ([book, book.borrows.build]) do |f|%>
          <%= f.hidden_field :status, value: "waiting accept"%>
            <%if user_signed_in?%>
                <% unless current_user.borrows.where( {book_id: book.id, status: ["waiting accept", "accept"]}).exists? || book.quantity_in_stock.nil? %>
                    <%= button_tag type: 'submit', class: "btn btn-primary", data: {confirm: "Do you want borrow #{book.name}"} do %>
                        <i class="fa fa-plus" aria-hidden="true"></i>
                    <% end %>
                <%end%>
            <%else%>
              <%= button_tag type: 'submit', class: "btn btn-primary" do %>
                  <i class="fa fa-plus" aria-hidden="true"></i>
                <% end %>
            <%end%>
        <%end%>    
  </div>
</div>
</div>
<%end%>
</div>
<%=will_paginate books%>
</div>